namespace QueensBackground {
    export const queens = [
        ["Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null],
        ["Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null],
        ["Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null],
        ["Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null],
        [null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null],
        [null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null],
        [null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null],
        [null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null],
        [null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null],
        [null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null],
        [null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null],
        [null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null],
        [null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null],
        [null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null],
        [null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null],
        [null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null],
        [null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null],
        [null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null],
        [null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null],
        [null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null],
        [null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null],
        [null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null],
        [null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen"],
        [null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null],
        [null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null],
        [null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null],
        [null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null],
        [null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null],
        [null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null],
        [null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null],
        [null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null],
        [null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen"],
        [null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null],
        [null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null],
        [null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null],
        [null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen"],
        [null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null],
        [null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen"],
        [null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null],
        [null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null],
        [null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null],
        [null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null],
        [null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, null, null, null, null, "Queen", null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null],
        [null, null, null, null, null, null, null, "Queen", null, null, "Queen", null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null],
        [null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, "Queen", null, null, null, null, null, null, null, null, null, null, null, null, "Queen", null, null, null, null, null, "Queen", null, null, null],
    ]
    let queensIndex

    let body = document.getElementsByTagName('body')[0]
    let ul = document.createElement("ul")
    ul.className = 'background'
    for (let i = 0; i < queens[0].length; i++) {
        let li = document.createElement("li")
        ul.appendChild(li)
        li.className = 'square'
    }
    body.appendChild(ul)

    function setIndex () {
        queensIndex = Math.floor(Math.random()*queens.length)
    }
    function renderQueens() {
        setIndex()
        let squares = document.getElementsByClassName('square')
        let board = queens[queensIndex]
        for(let i = 0; i < board.length; i++) {
            if (board[i]) {
                squares[i].classList.add('queen')
            } else {
                squares[i].classList.remove('queen')
            }
        }
    }
    renderQueens()

    setInterval(function () {
        renderQueens()
    }, 5000);
}
